MNT Update js-prs-issue workflow to include dependabot alerts
silverstripe/.github pull request #124
Opened 2023-10-03 00:49 UTC by GuySartorelli

Adds a new section to the js PRs issue for checking dependabot alerts.
Only includes URLs for supported repos in the latest stable major release line, and only if they have a package.json file.

## Issue
- https://github.com/silverstripeltd/product-issues/issues/812

2023-10-03 00:51 UTC, GuySartorelli commented on .github/workflows/js-prs-issue.yml
> +                echo "- $githubRef: Unable to check package.json, response was $response.\\n";
Have to have an _escaped_ new line here so it outputs correctly in the issue.

2023-10-03 20:49 UTC, emteknetnz requested changes

2023-10-03 20:49 UTC, emteknetnz commented on .github/workflows/js-prs-issue.yml
> +          if ! jq -e '.' __modules.json >/dev/null 2>&1; then
```suggestion
          if ! [[ $(jq -e '.' __modules.json >/dev/null 2>&1) ]]; then
```
Make the if conditional consistent with all the other workflow files. This is untested, though it'll be something like this

2023-10-03 20:49 UTC, emteknetnz commented on .github/workflows/js-prs-issue.yml
> +          curl -s -o __modules.json https://raw.githubusercontent.com/silverstripe/supported-modules/5/modules.json
This is hardcoded to 5, it'll be one of those things that silently breaks when we go to 6.

You can get the default branch from `https://api.github.com/repos/silverstripe/supported-modules` on the `default_branch` node

2023-10-03 20:49 UTC, emteknetnz commented on .github/workflows/js-prs-issue.yml
> +          # Get list of markdown links for supported module dependabot stuff
```suggestion
          # Create a list of markdown links for supported module dependabot stuff
```

2023-10-03 20:49 UTC, emteknetnz commented on .github/workflows/js-prs-issue.yml
> +            ${{ env.ALERTS_LIST }}
Also add in a "Delete temporary files" step to be consistent with other workflows e.g. https://github.com/silverstripe/gha-tag-release/blob/1/action.yml#L221 - you'll want to delete __modules.json.  It's done in other workflows to ensure we don't do things like accidentally commit temporarly files, I know it's not necessary in this context though it's a good practice

2023-10-03 20:52 UTC, GuySartorelli commented on .github/workflows/js-prs-issue.yml
> +          if ! jq -e '.' __modules.json >/dev/null 2>&1; then
This was directly copied from gha-ci:
https://github.com/silverstripe/gha-ci/blob/1/.github/workflows/ci.yml#L854-L858

I'm inclined to leave it as is since we know this works.

2023-10-03 20:54 UTC, GuySartorelli commented on .github/workflows/js-prs-issue.yml
> +          curl -s -o __modules.json https://raw.githubusercontent.com/silverstripe/supported-modules/5/modules.json
We discussed this offline - we've already hardcoded this in several places and in this case it'll only be a problem once and then we'll catch it.

2023-10-03 20:59 UTC, GuySartorelli commented on .github/workflows/js-prs-issue.yml
> +            ${{ env.ALERTS_LIST }}
Done

2023-10-03 21:00 UTC, GuySartorelli commented on .github/workflows/js-prs-issue.yml
> +          # Get list of markdown links for supported module dependabot stuff
Done

2023-10-03 21:06 UTC, GuySartorelli commented on .github/workflows/js-prs-issue.yml
> +          if ! jq -e '.' __modules.json >/dev/null 2>&1; then
We discussed this offline - I'll update it in both places.

2023-10-03 21:58 UTC, GuySartorelli commented on .github/workflows/js-prs-issue.yml
> +          if ! jq -e '.' __modules.json >/dev/null 2>&1; then
Done, and updated the links in the issue description for a re-run of this.

Note that I have ended up with `if ! [[ $(jq -e '.' __modules.json) ]] >/dev/null 2>&1; then`. We can't have the `>/dev/null 2>&1` part inside the brackets because then of course the `$()` has no output to capture.

2023-10-03 22:22 UTC, emteknetnz requested changes

2023-10-03 22:22 UTC, emteknetnz commented on .github/workflows/js-prs-issue.yml
> +          if ! [[ $(jq -e '.' __modules.json) ]] >/dev/null 2>&1; then
```suggestion
          if ! [[ $(jq -e '.' __modules.json > /dev/null 2>&1) ]] ; then
```
Isn't this what we want?

Actually this is probably better, it's done elsewhere quite a bit when dealing with jq()

```
MODULES=$(jq -e '.' __modules.json) || true
if [[ $MODULES == "" ]]; then
```
Where `|| true` prevents github actions from halting because of the non zero exit code thrown by jq

2023-10-03 22:32 UTC, GuySartorelli commented on .github/workflows/js-prs-issue.yml
> +          if ! jq -e '.' __modules.json >/dev/null 2>&1; then
This discussion is moved to https://github.com/silverstripe/.github/pull/124#discussion_r1344808107

2023-10-03 22:38 UTC, GuySartorelli commented on .github/workflows/js-prs-issue.yml
> +          if ! [[ $(jq -e '.' __modules.json) ]] >/dev/null 2>&1; then
Done. I don't think it's as clear what's happening there but I'm over it so I've made the change and added a comment about what it's doing.
Links in the description updated again with a new run on my fork.

2023-10-04 02:41 UTC, emteknetnz approved these changes

2023-10-04 02:42 UTC, merged