DOC Add default health files
silverstripe/.github pull request #67
Opened 2023-06-21 06:00 UTC by emteknetnz

CONTRIBUTING.md and SUPPORT.md are based on files from [framework](https://github.com/silverstripe/silverstripe-framework/), though they've been slightly altered

2023-06-21 06:58 UTC, GuySartorelli commented on README.md
This is not the organisation-wide readme file. See https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile#adding-a-public-organization-profile-readme

2023-06-22 04:59 UTC, emteknetnz commented on README.md
Updated

2023-06-22 05:26 UTC, GuySartorelli commented on README.md
This file shouldn't be deleted - see https://github.com/silverstripe/.github/issues/27

2023-06-23 06:47 UTC, emteknetnz commented on README.md
Reverted

2023-06-26 00:23 UTC, GuySartorelli requested changes

2023-06-26 00:23 UTC, GuySartorelli commented on CONTRIBUTING.md
> +**IMPORTANT: By supplying code to the SilverStripe core team in patches, tickets and pull requests, you agree to assign copyright of that code to SilverStripe Limited, on the condition that SilverStr
```suggestion
**IMPORTANT: By supplying code to the Silverstripe core team in issues and pull requests, you agree to assign copyright of that code to Silverstripe Limited, on the condition that Silverstripe Limited releases that code under the BSD license.**
```

2023-06-26 00:23 UTC, GuySartorelli commented on CONTRIBUTING.md
> +For more infomation read about [reporting security issues](https://docs.silverstripe.org/en/5/contributing/issues_and_bugs/#reporting-security-issues).
```suggestion
For more infomation read about [reporting security issues](https://docs.silverstripe.org/en/contributing/issues_and_bugs/#reporting-security-issues).
```
The other doc links omit the version number so makes sense to omit here too

2023-06-26 00:23 UTC, GuySartorelli commented on SUPPORT.md
> +Community support is provided by members of our open source community and is provided out of their good will. Please be kind, polite and corteous to those that try to help you; you may wish to refer
```suggestion
Community support is provided by members of our open source community and is provided out of their good will. Please be kind, polite and corteous to those that try to help you; you may wish to refer to our [code of conduct](https://docs.silverstripe.org/en/project_governance/code_of_conduct/).
```
The old link goes to v3

2023-06-26 00:23 UTC, GuySartorelli commented on SUPPORT.md
> +We recommend choosing the support forum based on the nature of your question:
```suggestion
We recommend choosing from the above support options based on the nature of your question:
```
"We recommend choosing the support forum" sounds like we're saying "Use the forum, as opposed to slack or stackoverflow" which doesn't seem to be the intent based on the sections that follow.

2023-06-26 00:23 UTC, GuySartorelli commented on profile/README.md
> +See [CONTRIBUTING.md](CONTRIBUTING.md) for information on contribute code, reporting security issues and code of conduct.
```suggestion
See [SUPPORT.md](/SUPPORT.md) for information on getting support.

### Contributing code

See [CONTRIBUTING.md](/CONTRIBUTING.md) for information on contribute code, reporting security issues and code of conduct.
```
These files aren't in the profile directory. I _think_ a preceding slash like this works - otherwise use `../`

2023-06-26 00:23 UTC, GuySartorelli commented on profile/README.md
Add some minimal blurb at the top of this file that says something about what Silverstripe CMS is.

e.g. [composer](https://github.com/composer) (which has a super minimal description) and [laravel](https://github.com/laravel) (which goes into more depth)

2023-06-26 00:23 UTC, GuySartorelli commented on profile/README.md
> +This repository is also used to track meta issues affecting a wide-ranging list of Silverstripe CMS modules. E.g. broken builds, changing CI configuration across multiple repos, issues on repos not i
This part about general issue tracking should go in the main README file for this repository, rather than the organisation-level readme.

2023-06-26 01:18 UTC, emteknetnz commented on CONTRIBUTING.md
> +**IMPORTANT: By supplying code to the SilverStripe core team in patches, tickets and pull requests, you agree to assign copyright of that code to SilverStripe Limited, on the condition that SilverStr
Updated

2023-06-26 01:18 UTC, emteknetnz commented on CONTRIBUTING.md
> +For more infomation read about [reporting security issues](https://docs.silverstripe.org/en/5/contributing/issues_and_bugs/#reporting-security-issues).
Updated

2023-06-26 01:18 UTC, emteknetnz commented on SUPPORT.md
> +Community support is provided by members of our open source community and is provided out of their good will. Please be kind, polite and corteous to those that try to help you; you may wish to refer
Updated

2023-06-26 01:19 UTC, emteknetnz commented on SUPPORT.md
> +We recommend choosing the support forum based on the nature of your question:
Updated

2023-06-26 01:23 UTC, emteknetnz commented on profile/README.md
Added

2023-06-26 01:23 UTC, emteknetnz commented on profile/README.md
> +See [CONTRIBUTING.md](CONTRIBUTING.md) for information on contribute code, reporting security issues and code of conduct.
Updated

2023-06-26 01:24 UTC, emteknetnz commented on profile/README.md
> +This repository is also used to track meta issues affecting a wide-ranging list of Silverstripe CMS modules. E.g. broken builds, changing CI configuration across multiple repos, issues on repos not i
Updated

2023-06-26 03:33 UTC, GuySartorelli approved these changes

2023-06-26 03:33 UTC, merged